[source]
repository = "https://github.com/miyake-ken/prompts"
kind = "tweet"
channel = "#hermes_home"
channel_id = "C0BBHF3REDS"
url = "https://x.com/i/status/2080929224060444811"
status_id = "2080929224060444811"
export_batch = "remaining"
export_batch_index = 55

[author]
name = "Hiro"
handle = "hiro1noue"

[metadata]
posted_at = "Sat Jul 25 08:12:43 +0000 2026"

[content]
text = """
たまたまpwnの動画見てたらめっちゃ面白い
https://youtu.be/EFIYGzv-VWw?si=-smcL65hb3AIUCKR
"""
