[source]
repository = "https://github.com/miyake-ken/prompts"
kind = "tweet"
channel = "#hermes_home"
channel_id = "C0BBHF3REDS"
url = "https://x.com/i/status/2081547228972478613"
status_id = "2081547228972478613"
export_batch = "remaining"
export_batch_index = 50

[author]
name = "zztkm"
handle = "zztkm"

[metadata]
posted_at = "Mon Jul 27 01:08:27 +0000 2026"

[content]
text = """
メモ: https://astgrep.com/advanced/prompting#using-ast-grep-with-ai-tools

ast-grep を pi で使うようにしてみる（多分ツールに関するシステムプロンプトを更新するでも良いし、単純に AGENTS.md でも行けそう
"""
